if (WIN32 AND CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
	if (NOT "x${CMAKE_CXX_SIMULATE_ID}" STREQUAL "xMSVC")
		message(FATAL_ERROR "clang on windows is not supported in gnu mode")
	endif()
	set(WIN_MSVC_CLANG TRUE)
elseif (MSVC)
	set(WIN_MSVC_CLANG TRUE)
else()
	set(WIN_MSVC_CLANG FALSE)
endif()

if (${WIN_MSVC_CLANG})
	if (NOT BUILD_SHARED_LIBS)
		string(REPLACE "/GR" "" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
	endif()
	if (${CMAKE_CXX_COMPILER_ID} STREQUAL "Clang")
		set(CLANG_CL TRUE)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Xclang -Wno-c99-extensions")
		if (NOT BUILD_SHARED_LIBS)
			set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Xclang -fno-rtti -Xclang -fno-rtti-data")
		endif()
	else()
		set(CLANG_CL FALSE)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Gy /MP")
		if (NOT BUILD_SHARED_LIBS)
			set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /GR-")
		endif()
	endif()
	set(COMPILE_DEFS ${COMPILE_DEFS} _UNICODE UNICODE)
	if(CLANG_CL AND NOT BUILD_SHARED_LIBS)
		set(COMPILE_DEFS ${COMPILE_DEFS} _HAS_STATIC_RTTI=0)
	endif()
elseif(WIN32 AND MINGW)	
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++20 -Wno-attributes -fvisibility=hidden")
	if (NOT BUILD_SHARED_LIBS)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-rtti")
	endif()
	set(COMPILE_DEFS WINVER=0x0600 _WIN32_WINNT=0x0600)
elseif (NOT WIN32)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++20 -Wno-attributes -fvisibility=hidden")
	if (NOT BUILD_SHARED_LIBS)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-rtti")
	endif()
endif()